# Generated by Django 6.1.1 on 2026-09-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="updataed_at",
            new_name="updated_at",
        ),
    ]
