# Generated by Django 6.1.1 on 2026-09-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_updataed_at_task_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"get_latest_by": "-created_at"},
        ),
    ]
