# Generated by Django 6.1.1 on 2026-09-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"get_latest_by": "-created_at", "ordering": ["-created_at"]},
        ),
    ]
